spring:
  h2: # h2
    console:
      enabled: true
      path: /h2
  datasource: # datasource
    url: "jdbc:h2:./SERVICE2DATA"
    driver-class-name: org.h2.Driver
    username: sa
  jpa: # JPA
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: teste2-service
server:
  port: 8083
  servlet:
    context-path: /service2

zipkin:
  base-url: http://localhost:9411/