spring:
  h2: # h2
    console:
      enabled: true
      path: /h2
  datasource: # datasource
    url: "jdbc:h2:./SERVICE3DATA"
    driver-class-name: org.h2.Driver
    username: sa
  jpa: # JPA
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: teste3-service
server:
  port: 8084
  servlet:
    context-path: /service3

zipkin:
  base-url: http://localhost:9411/