server:
  port: 8082
  servlet:
    context-path: /service1

spring:
  h2: # h2
    console:
      enabled: true
      path: /h2
  datasource: # datasource
    url: "jdbc:h2:./SERVICE1DATA"
    driver-class-name: org.h2.Driver
    username: sa
  jpa: # JPA
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: teste1-service

zipkin: ## configuração do centralizador de log
  base-url: http://localhost:9411/
